#!/usr/bin/env sh
set -eu

aube() {
  npx -y @endevco/aube@1.8.0 "$@"
}

aube exec lint-staged
aube run quality

(
  cd apps/android
  ./gradlew spotlessCheck :app:compileDebugKotlin :app:lintDebug :app:testDebugUnitTest
)
