#!/usr/bin/env sh
set -eu

aube() {
  npx -y @endevco/aube@1.4.0 "$@"
}

aube exec lint-staged
aube run format
aube run lint

(
  cd apps/android
  ./gradlew spotlessApply :app:compileDebugKotlin :app:lintDebug :app:testDebugUnitTest
)
