name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '17 4 * * 1'

permissions:
  contents: write
  issues: write
  pull-requests: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v46.1.14
        with:
          configurationFile: .github/renovate-global.js
          renovate-version: 43.150.0
          token: ${{ secrets.RENOVATE_TOKEN || github.token }}
        env:
          RENOVATE_REPOSITORY_CACHE: enabled
